### ISSUE TITLE
Nested AvroModel definitions create invalid Avro schemas

### ISSUE THREAD

**Issue by nhuber-tc** [marcosschroh/dataclasses-avroschema#114]
**Describe the bug**
When building a nested data structure of records, if you have multiple fields with the same type, you can end up generating a schema that tried to re-use the record names.

This seems very similar to #100, but the error occurs a level removed from where we can define an alternative name for the redefined field.

**To Reproduce**
```
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
import fastavro


@dataclass
class C(AvroModel):
    pass


@dataclass
class B(AvroModel):
    c: C


@dataclass
class A(AvroModel):
    b1: B
    b2: B

fastavro.parse_schema(A.avro_schema_to_python())
```
```
Traceback (most recent call last):
  File "sample.py", line 21, in <module>
    fastavro.parse_schema(A.avro_schema_to_python())
  File "fastavro/_schema.pyx", line 100, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 239, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 284, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 239, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 284, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 231, in fastavro._schema._parse_schema
fastavro._schema_common.SchemaParseException: redefined named type: c_record
```

For completions sake, here is what the generated schema looks like
```
{'doc': 'A(b1: __main__.B, b2: __main__.B)',
 'fields': [{'name': 'b1',
             'type': {'doc': 'B(c: __main__.C)',
                      'fields': [{'name': 'c',
                                  'type': {'doc': 'C()',
                                           'fields': [],
                                           'name': 'c_record',
                                           'type': 'record'}}],
                      'name': 'b1_record',
                      'type': 'record'}},
            {'name': 'b2',
             'type': {'doc': 'B(c: __main__.C)',
                      'fields': [{'name': 'c',
                                  'type': {'doc': 'C()',
                                           'fields': [],
                                           'name': 'c_record',
                                           'type': 'record'}}],
                      'name': 'b2_record',
                      'type': 'record'}}],
 'name': 'A',
 'type': 'record'}
```

This only seems to be the case when having the 2 types of a `B` in the parent class `A`, where itself has a type of another AvroModel class, `C` in this example.

**Expected behavior**
The schema should be constructed properly, without using a redefined name. Maybe it could

**Comment by marcosschroh** [comment]
Thanks for submitting this issue. I will try to take a look asap

**Comment by marcosschroh** [comment]
I have looked this issue and we need to solve it using the namespaces:

```python
from dataclasses_avroschema import AvroModel
from dataclasses import dataclass
import fastavro


@dataclass
class C(AvroModel):
    pass


@dataclass
class B(AvroModel):
    c: C

    class Meta:
        namespace = "my.name.space"


@dataclass
class A(AvroModel):
    b1: B
    b2: B
```

and the generated schema should be:

```python
schema = {'type': 'record',
 'name': 'A',
 'fields': [{'name': 'b1',
   'type': {'type': 'record',
    'name': 'b1_record',
    'fields': [{'name': 'c',
      'type': {'type': 'record',
       'name': 'c_record',
       'fields': [],
       'doc': 'C()'}}],
    'doc': 'B(c: __main__.C)',
    'namespace': 'my.name.space'}},
  {'name': 'b2', 'type': 'my.name.space.b1_record'}],  # using the namespace
 'doc': 'A(b1: __main__.B, b2: __main__.B)'}
```

result:

```python
{'type': 'record',
 'doc': 'A(b1: __main__.B, b2: __main__.B)',
 'name': 'A',
 'fields': [{'name': 'b1',
   'type': {'type': 'record',
    'doc': 'B(c: __main__.C)',
    'name': 'my.name.space.b1_record',
    'fields': [{'name': 'c',
      'type': {'type': 'record',
       'doc': 'C()',
       'name': 'my.name.space.c_record',
       'fields': []}}]}},
  {'name': 'b2', 'type': 'my.name.space.b1_record'}],
 '__fastavro_parsed': True,
 '__named_schemas': {'A': {'type': 'record',
   'doc': 'A(b1: __main__.B, b2: __main__.B)',
   'name': 'A',
   'fields': [{'name': 'b1',
     'type': {'type': 'record',
      'doc': 'B(c: __main__.C)',
      'name': 'my.name.space.b1_record',
      'fields': [{'name': 'c',
        'type': {'type': 'record',
         'doc': 'C()',
         'name': 'my.name.space.c_record',
         'fields': []}}]}},
    {'name': 'b2', 'type': 'my.name.space.b1_record'}]},
  'my.name.space.b1_record': {'type': 'record',
   'doc': 'B(c: __main__.C)',
   'name': 'my.name.space.b1_record',
   'fields': [{'name': 'c',
     'type': {'type': 'record',
      'doc': 'C()',
      'name': 'my.name.space.c_record',
      'fields': []}}]},
  'my.name.space.c_record': {'type': 'record',
   'doc': 'C()',
   'name': 'my.name.space.c_record',
   'fields': []}}}
```

I think with this solution we can go further and use `MyModel.__name__` to generate the record names and we won't have duplicates any more @kevinkjt2000
