### ISSUE TITLE
Invalid schema when record is referenced only by two different child records

### ISSUE THREAD

**Issue by iperry83** [marcosschroh/dataclasses-avroschema#145]
**Describe the bug**
Similar to #114 (but not identical), when two nested records (of differing types) both have a field of the same record type, but this record type does not exist in the parent record, the generated schema will redefine the common, inner record type.

**To Reproduce**
```python
from dataclasses import field
from typing import List, Optional


from dataclasses_avroschema import AvroModel
from fastavro import parse_schema


class Location(AvroModel):
    lat: float
    long: float
    altitude: Optional[float] = None
    bearing: Optional[float] = None


class Photo(AvroModel):
    filename: str
    data: bytes
    width: int
    height: int
    geo_tag: Optional[Location] = None


class Video(AvroModel):
    filename: str
    data: bytes
    duration: int
    geo_tag: Optional[Location] = None


class HolidayAlbum(AvroModel):
    album_name: str
    photos: List[Photo] = field(default_factory=list)
    videos: List[Video] = field(default_factory=list)

    class Meta:
        namespace = "test.namespace"


parse_schema(HolidayAlbum.avro_schema_to_python())
```

```
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    parse_schema(HolidayAlbum.avro_schema_to_python())
  File "fastavro/_schema.pyx", line 106, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 245, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 290, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 190, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 245, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 290, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 115, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 237, in fastavro._schema._parse_schema
fastavro._schema_common.SchemaParseException: redefined named type: test.namespace.Location
```

**Expected behavior**
A valid schema is generated, with `test.namespace.Location` only defined the first time it is encountered.

**Comment by marcosschroh** [comment]
With the new release should work fine. Closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/148
