### ISSUE TITLE
fastavro throws `UnknownType` on serialization for certain set of schema

### ISSUE THREAD

**Issue by tilmann-bartsch** [marcosschroh/dataclasses-avroschema#199]
**Describe the bug**
I found another (similar to  #196) combination of schemas which throw an error on serialization as shown below. The error is also present in the latest version `0.31.1`.

**To Reproduce**
```python
from dataclasses import dataclass
from dataclasses_avroschema import AvroModel


@dataclass
class A(AvroModel):
    class Meta:
        namespace = "namespace"


@dataclass
class B(AvroModel):
    a: A


@dataclass
class C(AvroModel):
    a: A


@dataclass
class D(AvroModel):
    b: B
    c: C


if __name__ == "__main__":
    a = A()
    b = B(a=a)
    c = C(a=a)
    d = D(b=b, c=c)
    
    d.serialize()
    c.serialize()
```
throws
```
Traceback (most recent call last):
  File "/home/tbartsch/test/new-avro-file.py", line 36, in <module>
    c.serialize()
  File "/home/tbartsch/test/venv/lib/python3.10/site-packages/dataclasses_avroschema/schema_generator.py", line 147, in serialize
    return serialize(self.asdict(), schema, serialization_type=serialization_type)
  File "/home/tbartsch/test/venv/lib/python3.10/site-packages/dataclasses_avroschema/serialization.py", line 20, in serialize
    fastavro.schemaless_writer(file_like_output, schema, payload)
  File "fastavro/_write.pyx", line 785, in fastavro._write.schemaless_writer
  File "fastavro/_schema.pyx", line 118, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 257, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 302, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 141, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: namespace.A
```

**Expected behavior**
The code above show run without error.

**Comment by tilmann-bartsch** [comment]
When changing the order of fields `b` and `c` in `D` like so
```
@dataclass
class D(AvroModel):
    b: B
    c: C
```
then the problem does not occur.

**Comment by stfines-clgx** [comment]
I continue to get this error even with the new version
