### ISSUE TITLE
ModelGenerator's output raises NameError for decimal fields

### ISSUE THREAD

**Issue by rgson** [marcosschroh/dataclasses-avroschema#233]
**Describe the bug**
Code generated by the `ModelGenerator` for schemas containing a decimal logical type field cannot run due to a missing import.

**To Reproduce**
```py
import dataclasses_avroschema

schema = {
    "type": "record",
    "name": "demo",
    "fields": [
        {
            "name": "foo",
            "type": {
                "type": "bytes",
                "logicalType": "decimal",
                "precision": 10,
                "scale": 3
            }
        }
    ]
}
code = dataclasses_avroschema.ModelGenerator().render(schema=schema)

with open("/tmp/generated_code.py", "w") as f:
    print(code, file=f)
```
```sh
python3 /tmp/generated_code.py
```
```
Traceback (most recent call last):
  File "/tmp/generated_code.py", line 7, in <module>
    class Demo(AvroModel):
  File "/tmp/generated_code.py", line 8, in Demo
    foo: decimal.Decimal = types.Decimal(scale=3, precision=10)
                           ^^^^^
NameError: name 'types' is not defined. Did you mean: 'type'?
```

**Expected behavior**
Loadable code without the `NameError`.

**Comment by marcosschroh** [comment]
Probably it is missing an import on the top. I will check it
