### ISSUE TITLE
`Internal Parser Exception` when serializing empty schema/ model with `avro-json` 

### ISSUE THREAD

**Issue by ciarandorney** [marcosschroh/dataclasses-avroschema#464]
**Describe the bug**
Serializing empty schema/model using `avro-json` results in a fastavro `Internal Parser Exception`

**To Reproduce**
```python
from uuid import UUID
from dataclasses_avroschema.pydantic import main as pydantic

class BaseMessage(pydantic.AvroBaseModel):

    pass

class Message(BaseMessage):

    message_uuid: UUID
```

**Expected behavior**
The should serialize without error 

**Actual behavior**
`avro` serialization:
```
>>> BaseMessage.fake().serialize()
b''
>>> Message.fake().serialize()
b'H4253ac66-2d8b-4470-ba92-25b0b97540d5
```

`avro-json` serialization:
```
>>> Message.fake().serialize(serialization_type="avro-json")
b'{"message_uuid": "4b82449d-4b8f-45e0-a991-e70d8643d20d"}'
>>> BaseMessage.fake().serialize(serialization_type="avro-json")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/dataclasses_avroschema/pydantic/main.py", line 69, in serialize
    return serialization.serialize(
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/dataclasses_avroschema/serialization.py", line 28, in serialize
    fastavro.json_writer(file_like_output, schema, [payload])
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/fastavro/json_write.py", line 79, in json_writer
    return writer(
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/fastavro/_write_py.py", line 739, in writer
    output.flush()
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/fastavro/_write_py.py", line 590, in flush
    self.encoder.flush()
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/fastavro/io/json_encoder.py", line 96, in flush
    self._parser.flush()
  File "/Users/ciarandorney/Library/Caches/pypoetry/virtualenvs/py3.10/lib/python3.10/site-packages/fastavro/io/parser.py", line 167, in flush
    raise Exception(f"Internal Parser Exception: {top}")
Exception: Internal Parser Exception: <fastavro.io.symbols.Sequence object at 0x1076a9c00>

```

**Comment by marcosschroh** [comment]
Yes. The problem is that `BaseMessage` does not have any fields, which is expected:

```python
print(BaseMessage.avro_schema())

# {"type": "record", "name": "BaseMessage", "fields": []}
```

Then is it nos possible to serialize an empty payload with a `avro schema` that does not have any fields. I think the error makes sense.

**Comment by ddevlin** [comment]
Hi @marcosschroh, we weren't sure if this was the expected behaviour as it's inconsistent between serialisation types, i.e. it's an error when serialising with the `avro-json` serialisation type, but with `avro` serialisation there's no error.

**Comment by marcosschroh** [comment]
Hi,

Even though it does not have too mush sense to have an `avro schema` without fields I agree that the behaviour is  inconsistent. We should return `b'{}'`

**Comment by ciarandorney** [comment]
> Even though it does not have too mush sense to have an `avro schema` without fields I agree that the behaviour is inconsistent. The output should be `b'{}'` for `avro-json` when the schema has not fields

Hi @marcosschroh, does it make sense to raise this issue over at [fastavro](https://github.com/fastavro/fastavro)? We could be patched here but that would involve checking for nested schemas with no fields on serialization.

Another example that produces the same internal parser error:
```
Avro schema:
{'type': 'record', 'name': 'NestedMessage', 'fields': [{'name': 'uuid', 'type': {'type': 'string', 'logicalType': 'uuid'}, 'default': '13673bf0-37ef-45bf-bf96-1d633ff90275'}, {'name': 'timestamp', 'type': {'type': 'long', 'logicalType': 'timestamp-millis'}, 'default': 1700052483304}, {'name': 'nested', 'type': {'type': 'record', 'name': 'Nested', 'fields': []}, 'default': {}}]} 

Payload:
{'uuid': UUID('16aca70b-37ff-46e5-b055-20c8bbc3ea08'), 'timestamp': datetime.datetime(2012, 8, 20, 19, 19, 19, tzinfo=datetime.timezone.utc), 'nested': {}}
```

**Comment by marcosschroh** [comment]
Does someone of you want to create the issue in `fastavro`? I can do it as well, no problem

**Comment by ciarandorney** [comment]
> Does someone of you want to create the issue in `fastavro`? I can do it as well, no problem

It's on my to-do 😅 If you want to do it go for it 😄

**Comment by ciarandorney** [comment]
https://github.com/fastavro/fastavro/issues/732
