### ISSUE TITLE
Cross-Models reference model generation

### ISSUE THREAD

**Issue by omer-shtivi** [marcosschroh/dataclasses-avroschema#552]
**Describe the bug**
I have a single AVSC file which have 4 models in it.
Those models are referencing each other.
When I'm trying to generate the python classes using the following code:
``` python
SCHEMA_FOLDER_PATH = Path("avro/schemas")
OUTPUT_FOLDER = Path("builder/build/tmp/avro_python/avros")
def main():
    OUTPUT_FOLDER.mkdir(parents=True, exist_ok=True)
    for file in SCHEMA_FOLDER_PATH.iterdir():
        if file.is_dir():
            schema_path = file.joinpath("schema.avsc")
            with schema_path.open() as schema_file:
                schemas_file = json.load(schema_file)
            with open(
                OUTPUT_FOLDER.joinpath(file.stem + ".py"), "w", encoding="utf-8"
            ) as f:
                f.write(model_generator.render_module(schemas=schemas_file))


if __name__ == "__main__":
    main()

```

I'm getting the following error:
```python
Traceback (most recent call last):
  File "/Users/omer/workspace/protos/avro/builder/builder.py", line 30, in <module>
    main()
  File "/Users/omer/workspace/protos/avro/builder/builder.py", line 25, in main
    f.write(model_generator.render_module(schemas=schemas_file))
  File "/Users/omer/.pyenv/versions/omer_default/lib/python3.9/site-packages/dataclasses_avroschema/model_generator/generator.py", line 211, in render_module
    self.validate_schema(schema=schema)
  File "/Users/omer/.pyenv/versions/omer_default/lib/python3.9/site-packages/dataclasses_avroschema/model_generator/generator.py", line 92, in validate_schema
    fastavro.parse_schema(schema)
  File "fastavro/_schema.pyx", line 173, in fastavro._schema.parse_schema
  File "fastavro/_schema.pyx", line 407, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 475, in fastavro._schema.parse_field
  File "fastavro/_schema.pyx", line 325, in fastavro._schema._parse_schema
  File "fastavro/_schema.pyx", line 267, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType: com.satori.generated.authz.avro.Note
```

**To Reproduce**
run the following code and try to render the following schema:
```
[
    {
        "type": "record",
        "name": "Note",
        "namespace": "com.abc.generated.authz.avro",
        "fields": [
            {
                "name": "note",
                "type": "string"
            },
            {
                "name": "type",
                "type": {
                    "type": "enum",
                    "name": "NoteType",
                    "namespace": "com.abc.generated.authz.avro",
                    "symbols": [
                        "GENERIC",
                        "AWS_POLICY_STMT_DENY_WITH_CONDITION",
                        "AWS_POLICY_STMT_SKIPPING_DENY_WITH_S3_NOT_RESOURCE",
                        "IAM_IDENTITY_CENTER_USER_DESCRIPTION"
                    ]
                }
            }
        ]
    },
    {
        "type": "record",
        "name": "PathElement",
        "namespace": "com.abc.generated.authz.avro",
        "fields": [
            {
                "name": "id",
                "type": "string"
            },
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "type",
                "type": {
                    "type": "enum",
                    "name": "PathElementType",
                    "namespace": "com.abc.generated.authz.avro",
                    "symbols": [
                        "USER",
                        "TEAM",
                        "GROUP",
                        "ROLE",
                        "DATASET",
                        "TABLE",
                        "PROJECT",
                        "FOLDER",
                        "ORGANIZATION",
                        "AWS_ACCOUNT",
                        "AWS_SERVICE",
                        "IAM_USER",
                        "IAM_GROUP",
                        "IAM_INLINE_POLICY",
                        "IAM_POLICY",
                        "IAM_ROLE",
                        "ROLE_SESSION",
                        "WEB_IDENTITY_SESSION",
                        "SAML_SESSION",
                        "FEDERATED_USER",
                        "ANONYMOUS_USER",
                        "CLUSTER",
                        "RESOURCE_POLICY",
                        "SHARE",
                        "CATALOG",
                        "SCHEMA",
                        "SERVICE_PRINCIPAL",
                        "IAM_IDENTITY_CENTER_USER",
                        "IAM_IDENTITY_CENTER_GROUP",
                        "PERMISSION_SET"
                    ]
                }
            },
            {
                "name": "notes",
                "type":
                {
                    "type": "array",
                    "items": "Note"
                }
            },
            {
                "name": "db_permissions",
                "type": {
                    "type": "array",
                    "items": "string"
                }
            }
        ]
    },
    {
        "type": "record",
        "name": "Asset",
        "namespace": "com.abc.generated.authz.avro",
        "fields": [
            {
                "name": "name",
                "type": {
                    "type": "array",
                    "items": "string"
                }
            },
            {
                "name": "type",
                "type": {
                    "type": "enum",
                    "name": "AssetType",
                    "symbols":
                    [
                        "TABLE",
                        "VIEW",
                        "MATERIALIZED_VIEW",
                        "S3_BUCKET",
                        "COLLECTION",
                        "TOAST_TABLE",
                        "FOREIGN_TABLE",
                        "PARTITION_TABLE",
                        "EXTERNAL",
                        "MANAGED",
                        "STREAMING_TABLE"
                    ]
                }
            },
            {
                "name": "notes",
                "type": {
                    "type": "array",
                    "items": "Note"
                }
            }
        ]
    },
    {
        "type": "record",
        "name": "Identity",
        "namespace": "com.abc.generated.authz.avro",
        "fields": [
            {
                "name": "id",
                "type": "string"
            },
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "type",
                "type": {
                    "type": "enum",
                    "name": "IdentityType",
                    "symbols": [
                        "USER",
                        "GROUP",
                        "ROLE",
                        "ROLE_LOGIN",
                        "SERVICE_ACCOUNT",
                        "WORKSPACE_ACCOUNT",
                        "CLOUD_IDENTITY_DOMAIN",
                        "AWS_ACCOUNT",
                        "AWS_SERVICE",
                        "IAM_USER",
                        "IAM_ROLE",
                        "ROLE_SESSION",
                        "WEB_IDENTITY_SESSION",
                        "SAML_SESSION",
                        "FEDERATED_USER",
                        "ANONYMOUS_USER",
                        "ACCOUNT",
                        "DB_USER",
                        "ORG_USER",
                        "CLUSTER",
                        "SERVICE_PRINCIPAL",
                        "IAM_IDENTITY_CENTER_USER"
                    ]
                }
            },
            {
                "name": "notes",
                "type": {
                    "type": "array",
                    "items": "Note"
                }
            }
        ]
    },
    {
        "type": "record",
        "name": "Entry",
        "namespace": "com.abc.generated.authz.avro",
        "fields": [
            {
                "name": "asset",
                "type": "Asset"
            },
            {
                "name": "path",
                "type": {
                    "type": "array",
                    "items": "PathElement"
                }
            },
            {
                "name": "identity",
                "type": "Identity"
            },
            {
                "name": "permission",
                "type": {
                    "type": "enum",
                    "name": "PermissionLevel",
                    "symbols": [
                        "UNKNOWN",
                        "READ",
                        "WRITE",
                        "FULL"
                    ]
                }
            }
        ]
    }
]
```

**Expected behavior**
Expect that Python classes will be generated with cross class references

**Comment by Panaetius** [comment]
I believe the issue lies with validate schema validating each schema in isolation: https://github.com/marcosschroh/dataclasses-avroschema/blob/260e35023a8c2983aa3af6064622f20110effafd/dataclasses_avroschema/model_generator/generator.py#L211

from the looks of it, the code after that also renders each class in isolation, so even if the validation passed, it would break in generation

**Comment by omer-shtivi** [comment]
(avgro-gen2)[https://github.com/rbystrit/avro_gen] works with it successfully, but it looks unmaintained.
I don't mind doing the job myself, I just want to know before I invest time that the maintainers are open to receive the code

**Comment by marcosschroh** [comment]
Hi @omer-shtivi 

Please send a PR! Contributions are always welcome!

**Comment by marcosschroh** [comment]
@Panaetius If the validation is removed then it should work

**Comment by Panaetius** [comment]
https://gitlab.com/Jaumo/pyavro-gen also works with it and generates dataclasses-avrogen code as output, but:
- it looks semi maintained
- it only works if all schemas have the `doc` property set
- it doesn't handle enums properly
- it doesn't create proper `class Meta:` entries

I'm currently using that one with quite a bit of monkey patching, but would much prefer to use dataclasses-avroschema instead. But it might serve as a starting point? The code looks a little convoluted, though.

@marcosschroh that's great! That would definitely help, though having validation would be nice of course. I'm not familiar enough with the code base here, so I couldn't tell if it'd work. It just looked like it renders each class separately, so my guess was that there would need to be something to link them, i.e. make sure that class A's field actually references class B. or does this just work by accident? How would it behave if I have e.g. com.example.v1.Test and com.example.v2.test schemas side by side?

**Comment by omer-shtivi** [comment]
> Hi @omer-shtivi
> 
> Please send a PR! Contributions are always welcome!

Ok, so let me go through the code and come up with a suggestion

**Comment by omer-shtivi** [comment]
@marcosschroh let me know if the solution looks valid for you, and if anything else is required
