### ISSUE TITLE
Do default values work?

### ISSUE THREAD

**Issue by FreCap** [marcosschroh/dataclasses-avroschema#82]
**Describe the bug**
In the example it seems that fastavro supports default values, but when I try to deserialize a value without I get the following exception

**To Reproduce**
```
from dataclasses import dataclass

import typing

from dataclasses_avroschema import AvroModel, types


@dataclass
class User(AvroModel):
    "An User"
    name: str
    age: int
    pets: typing.List[str]
    accounts: typing.Dict[str, int]
    favorite_colors: types.Enum = types.Enum(["BLUE", "YELLOW", "GREEN"])
    country: str = "Argentina"
    address: str = None

    class Meta:
        namespace = "User.v1"
        aliases = ["user-v1", "super user"]

# IMPORTANT: this is a JSON generated by .fake, but with the **country** removed.
fake_user_json_without_country = b'{"name": "MgXqfDAqzbgJSTTHDXtN", "age": 551, "pets": ["aRvwODwbOWfrkxYYkJiI"], "accounts": {"DQSZRzofFrNCiOhhIOvX": 4431}, "favorite_colors": "GREEN",  "address": {"string": "YgmVDKhXctMgODKkhNHJ"}}'


fake_deserialized_instance = User.deserialize(fake_user_json_without_country, serialization_type="avro-json")
# throws exception "KeyError: 'country'"
```

Exception:
```
ANACONDA_PATH_ON_WIN\python.exe C:/Users/fcapponi/PycharmProjects/entity-service/server/src/entity_service/managers/db_json_schemas/db_json_schema.py
Traceback (most recent call last):
  File "MY_PROJECT_PATHdb_json_schema.py", line 53, in <module>
    fake_deserialized_instance = User.deserialize(fake_user_json, serialization_type="avro-json")
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\dataclasses_avroschema\schema_generator.py", line 94, in deserialize
    payload = serialization.deserialize(data, schema, serialization_type=serialization_type)
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\dataclasses_avroschema\serialization.py", line 43, in deserialize
    payload = list(records)[0]
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\_read_py.py", line 950, in _elems
    yield read_data(
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\_read_py.py", line 558, in read_data
    data = reader_fn(
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\_read_py.py", line 446, in read_record
    record[field['name']] = read_data(
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\_read_py.py", line 558, in read_data
    data = reader_fn(
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\_read_py.py", line 239, in read_utf8
    return decoder.read_utf8()
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\io\json_decoder.py", line 91, in read_utf8
    return self.read_value()
  File "ANACONDA_PATH_ON_WIN\lib\site-packages\fastavro\io\json_decoder.py", line 36, in read_value
    return self._current[self._key]
KeyError: 'country'

Process finished with exit code 1

```

**Expected behavior**
That it didn't throw an exception and added the default value

**Comment by marcosschroh** [comment]
Thanks for the report @FreCap . I think there is a bug in `fastavro`. I will take a look!

**Comment by scottbelden** [comment]
As the maintainer of fastavro, I think this is also a bug in fastavro. Default values should definitely work when reading from a binary avro format, but there is a bit of a different code path when reading from a JSON file. I have a feeling this isn't being handled correctly when reading from JSON as that reader is relatively new.

If you could open an issue in the fastavro repo (so I don't forget about this) I could try to fix it when I have a moment.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/dataclasses-avroschema/pull/89
